-- MySQL Script generated by MySQL Workbench
-- 12/11/16 14:24:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema battleground
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema battleground
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `battleground` DEFAULT CHARACTER SET utf8 ;
USE `battleground` ;

-- -----------------------------------------------------
-- Table `battleground`.`weapons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `battleground`.`weapons` (
  `Name` VARCHAR(100) NOT NULL,
  `Damage` INT(11) NULL DEFAULT NULL,
  `Rate_Of_Fire` INT(11) NULL DEFAULT NULL,
  `Mag_Size` INT(11) NULL DEFAULT NULL,
  `Overheat_Time` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `battleground`.`melees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `battleground`.`melees` (
  `name` VARCHAR(100) NOT NULL,
  `damage` INT(11) NULL DEFAULT NULL,
  `distance` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `battleground`.`grenades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `battleground`.`grenades` (
  `name` VARCHAR(100) NOT NULL,
  `damage` INT(11) NULL DEFAULT NULL,
  `cooldown` INT(11) NULL DEFAULT NULL,
  `speed` INT(11) NULL DEFAULT NULL,
  `parabolic` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `battleground`.`clones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `battleground`.`clones` (
  `Name` TEXT NOT NULL,
  `Health` INT(11) NULL DEFAULT NULL,
  `Speed` INT(11) NULL DEFAULT NULL,
  `Accuracy` DOUBLE NULL DEFAULT NULL,
  `Skill` DOUBLE NULL DEFAULT NULL,
  `weapon` VARCHAR(100) NULL DEFAULT NULL,
  `grenade` VARCHAR(100) NULL DEFAULT NULL,
  `melee` VARCHAR(100) NULL DEFAULT NULL,
  `Rank` TEXT NOT NULL,
  `image` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`Name`(100), `Rank`(100)),
  INDEX `weapon` (`weapon` ASC),
  INDEX `melee` (`melee` ASC),
  INDEX `grenade` (`grenade` ASC),
  CONSTRAINT `clones_ibfk_1`
    FOREIGN KEY (`weapon`)
    REFERENCES `battleground`.`weapons` (`Name`),
  CONSTRAINT `clones_ibfk_2`
    FOREIGN KEY (`melee`)
    REFERENCES `battleground`.`melees` (`name`),
  CONSTRAINT `clones_ibfk_3`
    FOREIGN KEY (`grenade`)
    REFERENCES `battleground`.`grenades` (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
